//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONGNGAY
    {
        public int MA_CCN { get; set; }
        public int MA_NV { get; set; }
        public int MA_LCC { get; set; }
        public Nullable<System.DateTime> THOIGIANBATDAU_CCN { get; set; }
        public Nullable<System.DateTime> THOIGIANKETTHUC_CCN { get; set; }
    
        public virtual LOAICHAMCONG LOAICHAMCONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
