//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using QuanLyNhanSu.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class KHOANLUONG : BaseViewModel
    {
        private int _MA_KL;
        public int MA_KL { get => _MA_KL; set { _MA_KL = value; OnPropertyChanged(); } }
        private int _MA_LL;
        public int MA_LL { get => _MA_LL; set { _MA_LL = value; OnPropertyChanged(); } }
        private int _MA_NV;
        public int MA_NV { get => _MA_NV; set { _MA_NV = value; OnPropertyChanged(); } }
        private Nullable<decimal> _SOTIEN_KL;
        public Nullable<decimal> SOTIEN_KL { get => _SOTIEN_KL; set { _SOTIEN_KL = value; OnPropertyChanged(); } }

        public virtual LOAILUONG LOAILUONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
