//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOANLUONG
    {
        public int MA_LL2 { get; set; }
        public int MA_LL { get; set; }
        public int MA_NV { get; set; }
        public Nullable<decimal> SOTIEN_KL { get; set; }
    
        public virtual LOAILUONG LOAILUONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
