//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using QuanLyNhanSu.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LOAILUONG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAILUONG()
        {
            this.KHOANLUONG = new HashSet<KHOANLUONG>();
        }

        private int _MA_LL;
        public int MA_LL { get => _MA_LL; set { _MA_LL = value; OnPropertyChanged(); } }
        private string _TEN_LL;
        public string TEN_LL { get => _TEN_LL; set { _TEN_LL = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOANLUONG> KHOANLUONG { get; set; }
    }
}
