//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAINGHIPHEP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAINGHIPHEP()
        {
            this.KHOANNGHIPHEP = new HashSet<KHOANNGHIPHEP>();
        }
    
        public int MA_LNP { get; set; }
        public string TEN_LNP { get; set; }
        public Nullable<bool> COLUONG_LNP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOANNGHIPHEP> KHOANNGHIPHEP { get; set; }
    }
}
