//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNSEntities : DbContext
    {
        public QLNSEntities()
            : base("name=QLNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGLUONG> BANGLUONG { get; set; }
        public virtual DbSet<CHAMCONGNGAY> CHAMCONGNGAY { get; set; }
        public virtual DbSet<CHITIETPHIEUCHI> CHITIETPHIEUCHI { get; set; }
        public virtual DbSet<HOSOUNGTUYEN> HOSOUNGTUYEN { get; set; }
        public virtual DbSet<KHOANNGHIPHEP> KHOANNGHIPHEP { get; set; }
        public virtual DbSet<LICHSUNHANVIEN> LICHSUNHANVIEN { get; set; }
        public virtual DbSet<LOAICHAMCONG> LOAICHAMCONG { get; set; }
        public virtual DbSet<LOAILUONG> LOAILUONG { get; set; }
        public virtual DbSet<LOAINGHIPHEP> LOAINGHIPHEP { get; set; }
        public virtual DbSet<NGAYNGHILE> NGAYNGHILE { get; set; }
        public virtual DbSet<NGHIPHEP> NGHIPHEP { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PHIEUCHI> PHIEUCHI { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBAN { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<UNGVIEN> UNGVIEN { get; set; }
        public virtual DbSet<KHOANLUONG> KHOANLUONG { get; set; }
    }
}
