//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGAYNGHILE
    {
        public int MA_NNL { get; set; }
        public Nullable<System.DateTime> NGAY_NNL { get; set; }
        public string TEN_NNL { get; set; }
    }
}
