//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using QuanLyNhanSu.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NGAYNGHILE : BaseViewModel
    {
        private int _MA_NNL;
        public int MA_NNL { get => _MA_NNL; set { _MA_NNL = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _NGAY_NNL;
        public Nullable<System.DateTime> NGAY_NNL { get => _NGAY_NNL; set { _NGAY_NNL = value; OnPropertyChanged(); } }
        private string _TEN_NNL;
        public string TEN_NNL { get => _TEN_NNL; set { _TEN_NNL = value; OnPropertyChanged(); } }
    }
}
