//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGHIPHEP
    {
        public int MA_NP { get; set; }
        public int MA_NV { get; set; }
        public int MA_KNP { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU_NP { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC_NP { get; set; }
        public string LIDO_NP { get; set; }
    
        public virtual KHOANNGHIPHEP KHOANNGHIPHEP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
