//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using QuanLyNhanSu.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BANGLUONG = new HashSet<BANGLUONG>();
            this.CHAMCONGNGAY = new HashSet<CHAMCONGNGAY>();
            this.KHOANLUONG = new HashSet<KHOANLUONG>();
            this.KHOANNGHIPHEP = new HashSet<KHOANNGHIPHEP>();
            this.LICHSUNHANVIEN = new HashSet<LICHSUNHANVIEN>();
            this.NGHIPHEP = new HashSet<NGHIPHEP>();
            this.PHIEUCHI = new HashSet<PHIEUCHI>();
            this.TAIKHOAN = new HashSet<TAIKHOAN>();
        }
    
        private int _MA_NV;
        public int MA_NV { get => _MA_NV; set { _MA_NV = value; OnPropertyChanged(); } }
        private int _MA_PB;
        public int MA_PB { get => _MA_PB; set { _MA_PB = value; OnPropertyChanged(); } }
        private string _HOTEN_NV;
        public string HOTEN_NV { get => _HOTEN_NV; set { _HOTEN_NV = value; OnPropertyChanged(); } }
        private Nullable<bool> _GIOITINH_NV;
        public Nullable<bool> GIOITINH_NV { get => _GIOITINH_NV; set { _GIOITINH_NV = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _NGAYSINH_NV;
        public Nullable<System.DateTime> NGAYSINH_NV { get => _NGAYSINH_NV; set { _NGAYSINH_NV = value; OnPropertyChanged(); } }
        private Nullable<bool> _TRANGTHAI_NV;
        public Nullable<bool> TRANGTHAI_NV { get => _TRANGTHAI_NV; set { _TRANGTHAI_NV = value; OnPropertyChanged(); } }
        private string _CHUCVU_NV;
        public string CHUCVU_NV { get => _CHUCVU_NV; set { _CHUCVU_NV = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _NGAYVAOLAM_NV;
        public Nullable<System.DateTime> NGAYVAOLAM_NV { get => _NGAYVAOLAM_NV; set { _NGAYVAOLAM_NV = value; OnPropertyChanged(); } }
        private string _EMAIL_NV;
        public string EMAIL_NV { get => _EMAIL_NV; set { _EMAIL_NV = value; OnPropertyChanged(); } }
        private string _SODIENTHOAI_NV;
        public string SODIENTHOAI_NV { get => _SODIENTHOAI_NV; set { _SODIENTHOAI_NV = value; OnPropertyChanged(); } }
        private string _DIACHI_NV;
        public string DIACHI_NV { get => _DIACHI_NV; set { _DIACHI_NV = value; OnPropertyChanged(); } }
        private string _AVATAR_NV;
        public string AVATAR_NV { get => _AVATAR_NV; set { _AVATAR_NV = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGLUONG> BANGLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONGNGAY> CHAMCONGNGAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOANLUONG> KHOANLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOANNGHIPHEP> KHOANNGHIPHEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUNHANVIEN> LICHSUNHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGHIPHEP> NGHIPHEP { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUCHI> PHIEUCHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOAN { get; set; }
    }
}
