//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BANGLUONG = new HashSet<BANGLUONG>();
            this.CHAMCONGNGAY = new HashSet<CHAMCONGNGAY>();
            this.KHOANLUONG = new HashSet<KHOANLUONG>();
            this.KHOANNGHIPHEP = new HashSet<KHOANNGHIPHEP>();
            this.LICHSUNHANVIEN = new HashSet<LICHSUNHANVIEN>();
            this.NGHIPHEP = new HashSet<NGHIPHEP>();
            this.PHIEUCHI = new HashSet<PHIEUCHI>();
            this.TAIKHOAN = new HashSet<TAIKHOAN>();
        }
    
        public int MA_NV { get; set; }
        public int MA_PB { get; set; }
        public string HOTEN_NV { get; set; }
        public Nullable<bool> GIOITINH_NV { get; set; }
        public Nullable<System.DateTime> NGAYSINH_NV { get; set; }
        public string CHUCVU_NV { get; set; }
        public Nullable<System.DateTime> NGAYVAOLAM_NV { get; set; }
        public string EMAIL_NV { get; set; }
        public string SODIENTHOAI_NV { get; set; }
        public string DIACHI_NV { get; set; }
        public string AVATAR_NV { get; set; }
        public Nullable<bool> TRANGTHAI_NV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGLUONG> BANGLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONGNGAY> CHAMCONGNGAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOANLUONG> KHOANLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOANNGHIPHEP> KHOANNGHIPHEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUNHANVIEN> LICHSUNHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGHIPHEP> NGHIPHEP { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUCHI> PHIEUCHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOAN { get; set; }
    }
}
