//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUCHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUCHI()
        {
            this.CHITIETPHIEUCHI = new HashSet<CHITIETPHIEUCHI>();
        }
    
        public int MA_PC { get; set; }
        public int MA_NV { get; set; }
        public Nullable<decimal> TRIGIA_PC { get; set; }
        public Nullable<System.DateTime> THOIGIANLAP_PC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUCHI> CHITIETPHIEUCHI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
