//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using QuanLyNhanSu.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN : BaseViewModel
    {
        private int _MA_TK;
        public int MA_TK { get => _MA_TK; set { _MA_TK = value; OnPropertyChanged(); } }
        private int _MA_NV;
        public int MA_NV { get => _MA_NV; set { _MA_NV = value; OnPropertyChanged(); } }
        private string _TENDANGNHAP_TK;
        public string TENDANGNHAP_TK { get => _TENDANGNHAP_TK; set { _TENDANGNHAP_TK = value; OnPropertyChanged(); } }
        private string _MATKHAU_TK;
        public string MATKHAU_TK { get => _MATKHAU_TK; set { _MATKHAU_TK = value; OnPropertyChanged(); } }
        private string _QUYEN_TK;
        public string QUYEN_TK { get => _QUYEN_TK; set { _QUYEN_TK = value; OnPropertyChanged(); } }

        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
