//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNGVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNGVIEN()
        {
            this.HOSOUNGTUYEN = new HashSet<HOSOUNGTUYEN>();
        }
    
        public int MA_UV { get; set; }
        public string HOTEN_UV { get; set; }
        public Nullable<bool> GIOITINH_UV { get; set; }
        public Nullable<System.DateTime> NGAYSINH_UV { get; set; }
        public string EMAIL_UV { get; set; }
        public string SODIENTHOAI_UV { get; set; }
        public string DIACHI_UV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSOUNGTUYEN> HOSOUNGTUYEN { get; set; }
    }
}
